[workspace]
resolver = "2"
members = [
    "basic-cache-logic",
    "basic-cache-entity",
    "basic-cache-proto",
    "basic-cache-server",
]

[workspace.dependencies]
blockscout-service-launcher = "0.10.0"