type: google.api.Service
config_version: 3

http:
  rules:
    
    - selector: blockscout.basicCache.v1.Cache.CreateSmartContract
      post: /api/v1/smart-contracts
      body: "*"

    - selector: blockscout.basicCache.v1.Cache.GetSmartContract
      get: /api/v1/chains/{chain_id}/smart-contracts/{address}:get
    
    #################### Health ####################

    - selector: blockscout.basicCache.v1.Health.Check
      get: /health

